spring.application.name=project

# Banco
spring.datasource.url=jdbc:mysql://localhost:3306/mybar_database?useTimezone=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# JWT
api.security.token.secret=12345